name: Sync Commits

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout first_repo
      uses: actions/checkout@v2
      with:
        repository: AniTamaryan/first_repo
        path: first_repo

    - name: Copy Files from second_repo
      run: |
         cp -r !(.[^.]*|.??*) ../first_repo/     

    - name: Commit and Push Changes
      run: |
        cd ../first_repo
        git config --global user.email "tamaryanani950@gmail.com"
        git config --global user.name "AniTAmaryan"
        git status -s
        git add .
        git commit -m "Sync changes from second_repo"
        git push

