name: Copy Files and Commit

on:
  push:
    branches:
      - main

jobs:
  copy-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout first repository
        uses: actions/checkout@v2
        with:
          repository: AniTamaryan/first_repo
          path: first_repo

      - name: Checkout second repository
        uses: actions/checkout@v2
        with:
          repository: AniTamaryan/second_repo
          path: second_repo

      - name: Get latest commit message
        run: |
          cd second_repo
          latest_commit_message=$(git log --pretty=format:%s -1)
          echo "::set-output name=message::$latest_commit_message"
        id: get_message

      - name: Copy files from second repository to first repository
        run: |
          cd second_repo
          for file in $(git diff-tree --no-commit-id --name-only -r HEAD); do
            cp -v "$file" "../first_repo/"
          done

      - name: Commit changes to first repository
        run: |
          cd first_repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "${{ steps.get_message.outputs.message }}"
          git push

